name: flood_prediction
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.16.0
  flutter_dotenv: ^5.1.0
  http: ^1.6.0
  flutter_map: ^8.3.1
  latlong2: ^0.10.1
  geolocator: ^14.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env
